/**
 * gen-client-manifest.ts
 *
 * Reads client/dist/ (produced by `vite build`) and generates
 * server/src/generated/client-manifest.ts with every file's content
 * embedded as a string or base64 literal.
 *
 * bun build --compile then bundles those literals into the binary,
 * producing a single self-contained executable.
 *
 * Usage: bun run scripts/gen-client-manifest.ts
 */

import { existsSync } from 'node:fs'
import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises'
import { extname, join, relative } from 'node:path'

const DIST_DIR = join(import.meta.dir, '../client/dist')
const OUT_FILE = join(import.meta.dir, '../server/src/generated/client-manifest.ts')

if (!existsSync(DIST_DIR)) {
	console.error(`client/dist not found — run 'bun run build' in the client package first`)
	process.exit(1)
}

const CONTENT_TYPES: Record<string, string> = {
	'.html': 'text/html; charset=utf-8',
	'.js': 'application/javascript; charset=utf-8',
	'.mjs': 'application/javascript; charset=utf-8',
	'.css': 'text/css; charset=utf-8',
	'.json': 'application/json; charset=utf-8',
	'.svg': 'image/svg+xml',
	'.png': 'image/png',
	'.jpg': 'image/jpeg',
	'.jpeg': 'image/jpeg',
	'.ico': 'image/x-icon',
	'.woff': 'font/woff',
	'.woff2': 'font/woff2',
	'.ttf': 'font/ttf',
	'.webp': 'image/webp',
	'.txt': 'text/plain; charset=utf-8',
	'.xml': 'application/xml',
}

const BINARY_EXTS = new Set(['.png', '.jpg', '.jpeg', '.ico', '.woff', '.woff2', '.ttf', '.webp'])

async function collectFiles(dir: string): Promise<Array<{ urlPath: string; filePath: string }>> {
	const entries = await readdir(dir, { withFileTypes: true })
	const files: Array<{ urlPath: string; filePath: string }> = []
	for (const entry of entries) {
		const fullPath = join(dir, entry.name)
		if (entry.isDirectory()) {
			files.push(...(await collectFiles(fullPath)))
		} else {
			const rel = relative(DIST_DIR, fullPath).replaceAll('\\', '/')
			files.push({ urlPath: '/' + rel, filePath: fullPath })
		}
	}
	return files
}

const files = await collectFiles(DIST_DIR)
const lines: string[] = []

for (const { urlPath, filePath } of files) {
	const ext = extname(filePath).toLowerCase()
	const contentType = CONTENT_TYPES[ext] ?? 'application/octet-stream'

	if (BINARY_EXTS.has(ext)) {
		const buf = await readFile(filePath)
		const b64 = buf.toString('base64')
		// Store binary files as base64; decoded at serve time
		lines.push(
			`  ${JSON.stringify(urlPath)}: { content: Buffer.from(${JSON.stringify(b64)}, 'base64').toString('binary'), contentType: ${JSON.stringify(contentType)}, binary: true }`,
		)
	} else {
		const text = await readFile(filePath, 'utf-8')
		// Use JSON.stringify for safe string escaping
		lines.push(
			`  ${JSON.stringify(urlPath)}: { content: ${JSON.stringify(text)}, contentType: ${JSON.stringify(contentType)}, binary: false }`,
		)
	}
}

await mkdir(join(import.meta.dir, '../server/src/generated'), { recursive: true })

const output = `// AUTO-GENERATED by scripts/gen-client-manifest.ts — do not edit manually.
// Re-run 'bun run gen:client' after each client build.
export type ClientAsset = { content: string; contentType: string; binary: boolean }
export const clientAssets: Record<string, ClientAsset> = {
${lines.join(',\n')}
}
export const hasClientAssets = true
`

await writeFile(OUT_FILE, output, 'utf-8')
console.log(`✓ Embedded ${files.length} client files → server/src/generated/client-manifest.ts`)
